### PR TITLE
Fix pip installs

### PR DESCRIPTION
**Pull request by fdimaio**
Pip installs now copy all necessary files.

### CODE REVIEW

**Comment by kleinhenz** [comment]
I think using `find_packages` is slightly more idiomatic than putting everything in the manifest.

```
from setuptools import setup, find_packages

setup(
    name='myPackage',
    packages=find_packages(),
)
```

**Comment by fdimaio** [comment]
> 



> I think using `find_packages` is slightly more idiomatic than putting everything in the manifest.

Ok, will update this.

**Comment by fdimaio** [comment]
OK, fixed.

**Review by aleaverfay — APPROVED** [review]
I can confirm that this fixes the `pip install .` installation :+1:

**Pull request merged**
