### PR TITLE
Aleaverfay/py3.9 torch1.11

### PR DESCRIPTION
**Pull request by aleaverfay**
Update the build environment for tmol to python3.9 and some of the more recent versions of many packages. This will help us use tmol along side other recent packages.

### CODE REVIEW

**Comment by aleaverfay** [comment]
@fdimaio Could you look at the racehorse-benchmark? I am not sure I understand why it's showing as failing.

**Comment by fdimaio** [comment]
> @fdimaio Could you look at the racehorse-benchmark? I am not sure I understand why it's showing as failing.

The script makes some plots at the end and uses 'seaborn' as a dependency to do so.  It's missing in the current environment.

I personally do not find the plots useful, so you can either remove the plotting or add seaborn to deps.

**Review by fdimaio — APPROVED** [review]
Mostly looks fine.  I approved, but before merging can you do the following:
1) Can you fix the seaborn issue (see comment)?
2) Can you remove the 'test' subfolder?

**Comment by fdimaio** [comment]
looks like it needs itermplot too

**Pull request merged**
