### PR TITLE
Dimaio/singularity test server

### PR DESCRIPTION
**Pull request by fdimaio**
Change test infrastructure to use singularity backend.

### CODE REVIEW

**Review by aleaverfay — APPROVED** [review]
LGTM

**Comment by aleaverfay** [comment]
Looks great, Frank. I’ll merge trunk into my PR when you’ve merged this
into trunk

**Comment by jflat06** [comment]
I don't see anything in the changes that references singularity. Is that outside of this PR?

**Comment by fdimaio** [comment]
> I don't see anything in the changes that references singularity. Is that outside of this PR?

Yes, singularity is running on the backend now.  This just changes to the testing pipeline to be compatible with the backend changes.

**Pull request merged**
